### ISSUE TITLE
Failed Community node update

### ISSUE THREAD

**Issue by marceldarvas** [bramkn/n8n-nodes-splitinbatches-advanced#2]
When navigating to the Community nodes page to check installed modules, I want to update this one from v0.1.0 to 0.2.4, I click update. This n8n gives me a green check mark in the bottom right with:
Package updated
n8n-nodes-splitinbatches-advanced updated to version 0.2.4

However, when I hit refresh on the page, I am still on the old version...

I've deactivated the workflow where I am using this node, but even then, I have this update loop bug... n8n is on the latest version

**Comment by bramkn** [comment]
you would probably need to reboot the instance for the update to take affect.

**Comment by bramkn** [comment]
to be clear, this has nothing to do with the node it self but how n8n updates them.
